  window.onload = function() {
    let navBar = document.getElementsByClassName("nav__wrap-links")[0];
    let links = document.createElement("div");
    links.setAttribute("class", "nav__wrap-link");
    links.classList.add("language");
    let navLinkLV = document.createElement("div");
    navLinkLV.setAttribute("class", "nav__item");
    let linkLV = document.createElement("a");
    linkLV.setAttribute("href", "/projekti/kulturekas");
    linkLV.setAttribute("class", "navigation-item");
    linkLV.innerHTML = "LV";
    navLinkLV.append(linkLV);
    links.append(navLinkLV);
    let navLinkEN = document.createElement("div");
    navLinkEN.setAttribute("class", "nav__item");
    let linkEN = document.createElement("a");
    linkEN.setAttribute("href", "/projekti/kulturekas?lang=EN");
    linkEN.setAttribute("class", "navigation-item");
    linkEN.innerHTML = "EN";
    linkEN.style.paddingRight = "0px";
    navLinkEN.append(linkEN);
    links.append(navLinkEN);
    navBar.append(links);
    // Get language
    let href = window.location.href;
    let url = new URL(href);
    let lang = url.searchParams.get('lang');
    if (lang == 'EN' ) {
      document.getElementById('hero-title').innerHTML = '3D kultūrēkas';
      document.getElementById('share').innerHTML = 'Share:';
      document.getElementById('subheading').innerHTML = `Discover the history of Liepaja with "3D kultūrēkas"`;
      let about = document.getElementById('about-project');
      about.firstElementChild.remove();
      about.insertAdjacentHTML("afterbegin",`<div class="rich-txt-blog w-richtext"><p>We have created an app called "3D kultūrēkas" that will allow Liepaja residents and visitors to view three historic buildings in Liepaja, which no longer exist today, using augmented reality technology on their smartphones:</p><ul role="list"><li>Liepaja Museum building in Aleja Park;</li><li>Liepaja German Theater;</li><li>Liepaja Great Horal Synagogue.</li></ul><p>“3D kultūrēkas” implemented within the framework of the project "Reconstruction of Historical Architecture of Liepaja in Augmented Reality, Part 3" with the support of the Liepaja Culture Administration.</p><p>&zwj;</p><p>Goals of the project:</p><ul role="list"><li>Promote the development of a creative, intellectual, and innovative environment in Liepaja for the professional growth of representatives of creative industries.</li><li>Promote local patriotism among Liepaja residents and educate about the architecture and history of Liepaja.</li><li>Promote the study, documentation, and accessibility of architectural historical heritage using modern technology options.</li><li>Develop a body of knowledge that promotes digital literacy, allowing technology to be used as an effective tool for professional activity and content consumption.</li><li>Promote the professional development of representatives of the architecture industry and the use of augmented reality in professional practice.</li></ul></div>`);
      document.getElementById('app-heading').innerHTML = 'App is available here:';
      document.getElementById('btn-ios').innerHTML = 'Download iOS app';
      document.getElementById('btn-android').innerHTML = 'Download Android app';
      document.getElementById('building-heading').innerHTML = 'About buildings';
      let firstBuilding = document.getElementById('building-first');
      firstBuilding.firstElementChild.remove();
      firstBuilding.insertAdjacentHTML("afterbegin",`<div class="rich-txt-blog w-richtext"><p><strong>The Liepaja Museum building</strong></p><p>The Liepaja Museum building was allocated by the City Council in September 1924 for the establishment of a museum in the former 8th Primary School building on Alejas (now Čakstes) Square. The museum was opened on November 30, 1924, and the collections of the Liepaja Society for the Promotion of Latvian Art, the Liepaja Society of Antiquities, the Teachers' Trade Union, and, of course, the Kurzeme Museum Society were housed under one roof. Over time, it became apparent that the Kurzeme Museum Society was the most stable of the four societies housed in the museum. In 1935, the City Council purchased the building at Kūrmājas Prospect for the needs of the museum.</p></div>`);
      let secondBuilding = document.getElementById('building-second');
      secondBuilding.firstElementChild.remove();
      secondBuilding.insertAdjacentHTML("afterbegin",`<div class="rich-txt-blog w-richtext"><p><strong>The Liepaja German Theater</strong></p><p>The theater was officially opened on April 15, 1804. The building was made of wood and had 350 seats, which was sufficient for the city of 4500 inhabitants. The design of the building was based on the theater in Jelgava. At that time, the relatively small city of Liepaja did not have a grand and luxurious theater like the large cities of Russia (Duchy of Courland and Semigallia was annexed to the Russian Empire in 1795), but it had the characteristics of Russian theater architecture of the time – columns, arches, etc. The Liepaja German Theater was the first professional theater in Liepaja. The German actor Walter Rauph worked here, who was later loved by the famous Latvian actress Anta Klints, whose real name was Anna Jekste. She never forgot Rauph's statement: "Even a small theater can have great art."</p><p>This building was demolished in 1924.</p></div>`);
      let thirdBuilding = document.getElementById('building-third');
      thirdBuilding.firstElementChild.remove();
      thirdBuilding.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p><strong>The Liepaja Great Choral Synagogue</strong></p><p>The Great Choral Synagogue of Liepaja was one of the 12 synagogues and prayer houses that operated in Liepaja before World War II. It was the most significant and artistically valuable of all the synagogues in Latvia. The Great Choral Synagogue of Liepaja was built in the period from 1870 to 1873 in the Neorenaissance style, based on the Oranienburger Straße Synagogue in Berlin. The Great Choral Synagogue of Liepaja was destroyed during the German occupation in July 1941. Due to the danger of detonating explosives in the center of the city, the synagogue was demolished by hand, and Jews were forced to do the work.</p></div>`);
      document.getElementById('instruction-heading').innerHTML =  'Instructions for use';
      let instructionMain = document.getElementById('instruction-main');
      instructionMain.firstElementChild.remove();
      instructionMain.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p>To view the 3D cultural buildings, you must allow the app to access your device's location and camera. On different devices, the buildings may be located in different places depending on the performance of the smartphone, weather conditions, surrounding environment, GPS signal. In the dark or near buildings that block the signal, the app may function with disruptions. Please be careful in traffic!</p><p>The buildings can be viewed in 3 ways:</p><ul role="list"><li>in a virtual space – the building models can be placed in a virtual space to closely examine the facades and architectural elements of the building;</li><li>on an image – the building models can be placed on an image that the app uses as a marker. When selecting the "Place on Image" option, you should aim your smartphone camera at a printed image or image on another device screen and the 3D model will be placed on this image when the app recognizes it. Download the images here;</li><li>in 3 locations in Liepaja – at the historical locations of the buildings, to appreciate the full-scale architecture and how the building looked historically and where it was located.</li></ul></div>`);
      document.getElementById('developers-heading').innerHTML = 'Project developed by';
      let developerJanis = document.getElementById('info-janis');
      developerJanis.firstElementChild.remove();
      developerJanis.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p><strong>Jānis Jaunsleinis</strong> – 3D architecture developer:</p><ul role="list"><li>Participated in the creation of a 3D model for the construction section for the reconstruction of Riga Technical University;&nbsp;</li><li>Created visualizations of buildings energy efficiency improvement projects;</li><li>He has researched many sources of pre-war photography and history of the city of Liepaja, therefore with the help of augmented reality and 3D modelling he can revive the lost architecture give people the opportunity to see the features of historical buildings.&nbsp;&nbsp;</li></ul></div>`);
      document.getElementById('how-city-heading').innerHTML = 'How to view the buildings in the city?';
      let howCity = document.getElementById('how-city-paragraph');
      howCity.firstElementChild.remove();
      howCity.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p>To view any of the buildings in the city, you need to be within 30 meters of the building's historical location. When within 30 meters of the building's former location, the text "Place building" will appear on the available building button.</p><p>Guidelines have been used for all buildings that must be used to place the buildings in their previous location.</p></div>`);
      document.getElementById('how-building-1-heading').innerHTML = 'How to view the Liepaja Museum building?';
      document.getElementById('step-1-1').innerHTML = 'Step 1';
      document.getElementById('step-1-2').innerHTML = 'Step 2';
      document.getElementById('step-1-3').innerHTML = 'Step 3';
      document.getElementById('txt-1-1').innerHTML = 'Go to Jāņa Čakstes Square, in Liepaja';
      document.getElementById('txt-1-2').innerHTML = 'Stand here with your back facing the direction of the Latvian flag';
      document.getElementById('txt-1-3').innerHTML = 'Place your phone so that the guidelines match the image and press the "Place" button';
      document.getElementById('how-building-2-heading').innerHTML = 'How to view the Liepaja German Theater?';
      document.getElementById('step-2-1').innerHTML = 'Step 1';
      document.getElementById('step-2-2').innerHTML = 'Step 2';
      document.getElementById('step-2-3').innerHTML = 'Step 3';
      document.getElementById('txt-2-1').innerHTML = 'Go to the intersection of Kungu and Malkas streets in Liepaja';
      document.getElementById('txt-2-2').innerHTML = 'Stand on Kungu Street facing the direction of Malkas Street';
      document.getElementById('txt-2-3').innerHTML = 'Place your phone so that the guidelines match the corner of the opposite building and press the "Place" button';
      document.getElementById('how-building-3-heading').innerHTML = 'How to view the Liepāja Great Horal Synagogue?';
      document.getElementById('step-3-1').innerHTML = 'Step 1';
      document.getElementById('step-3-2').innerHTML = 'Step 2';
      document.getElementById('step-3-3').innerHTML = 'Step 3';
      document.getElementById('txt-3-1').innerHTML = 'Go to the intersection of Kuršu and Rožu streets in Liepaja';
      document.getElementById('txt-3-2').innerHTML = 'Stand next to the road sign facing across Kuršu Street';
      document.getElementById('txt-3-3').innerHTML = 'Place your phone so that the guidelines match the image and press the "Place" button';
      document.getElementById('how-plane-heading').innerHTML = 'How to view the buildings in a virtual space?'
      let howPlane = document.getElementById('how-plane-paragraph');
      howPlane.firstElementChild.remove();
      howPlane.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p>You can view all the buildings in a small size by placing them in a virtual space. The buildings will best be placed in large rooms or outdoors, outside of rooms.</p><ol start="" role="list"><li>Open the "3D kultūrēkas " app;</li>
      <li>Choose "Place buildings" – "In virtual space"</li><li>Find a flat surface;</li><li>Wait at least 6 seconds for the phone to detect the surface;</li><li>When the phone recognizes the surface, it is possible to place the virtual space with buildings. It is possible to move around the virtual space and view the buildings from all sides.</li></ol></div>`);
      let developerKaspars = document.getElementById('info-kaspars');
      developerKaspars.firstElementChild.remove();
      developerKaspars.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p><strong>Kaspars Lēvalds</strong> – multimedia artist.</p><p>Kaspars:</p><ul role="list"><li>Graduate of the University of Liepaja, in the program New Media Art;</li><li>Within and outside the studies, he has created and participated in the creation of various augmented reality (VR, AR) works;</li><li>Participated in Augmented and Virtual Reality Hackathon 2018 and RIGA IFF GOES VR (2019), where together with the teams they gained the first and second place in creating virtual reality experiences;</li><li>Creates a variety of digital visual works – design and architecture and other types, using Unity and Unreal Engine game drivers.</li></ul></div>`);
      let developerArturs = document.getElementById('info-arturs');
      developerArturs.firstElementChild.remove();
      developerArturs.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p><strong>Arturs Vītiņš</strong> – programmer, augmented reality developer.</p><p>Arturs:</p><ul role="list"><li>For several years working as a civil engineer building design Ltd. AILE group;</li><li>Know several programming languages;</li><li>The project developed an application in the Unity environment for iOS and Android devices, as well as created augmented reality solutions.</li></ul></div>`);
      let eula = document.getElementById('eula');
      eula.firstElementChild.remove();
      eula.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog txt_align_centred mt_80 w-richtext"><p><a href="/projekti/3d-kulturekas-gala-lietotaja-licences-ligums">EULA</a></p><strong>&zwj;</strong></a>Use email address <a href="mailto:team@digip.lv">team@digip.lv</a>, to contact us in case of uncertainty, in matters related to marketing and when you need support.</p><p>&zwj;</p></div>`);
      document.getElementById('txt-liepaja').innerHTML = 'The app is supported by the Liepaja Culture Department';
      document.getElementById('how-img-heading').innerHTML = 'How to view the buildings on an image?';
      let image = document.getElementById('how-img-paragraph');
      image.firstElementChild.remove();
      image.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p>You can view all the buildings in a small size by placing them on an image.</p><ol start="" role="list"><li>Print out the image or open it on another device's screen;</li><li>Open the "3D kultūrēkas " app;</li><li>Choose "Place buildings" – "On image";</li><li>Aim your phone's camera at the image</li><li>The building will automatically be placed on the image and follow it.</li></ol></div>`);
      document.getElementById('subscript-first').innerHTML = 'Image from Liepaja Museum';
      document.getElementById('subscript-secound').innerHTML = 'Image from Liepaja Museum';
      document.getElementById('subscript-third').innerHTML = 'Picture from Open Public Fund "Liepaja Jewish Heritage"';
    }
  }
