// Language changer
window.onload = function() {
  let navBar = document.getElementsByClassName("nav__wrap-links")[2];
  let links = document.createElement("div");
  links.setAttribute("class", "nav__wrap-link");
  links.classList.add("language");
  let navLinkLV = document.createElement("div");
  navLinkLV.setAttribute("class", "nav__item");
  let linkLV = document.createElement("a");
  linkLV.setAttribute("href", "/projekti/3d-ekas");
  linkLV.setAttribute("class", "navigation-item");
  linkLV.innerHTML = "LV";
  navLinkLV.append(linkLV);
  links.append(navLinkLV);
  let navLinkEN = document.createElement("div");
  navLinkEN.setAttribute("class", "nav__item");
  let linkEN = document.createElement("a");
  linkEN.setAttribute("href", "/projekti/3d-ekas?lang=EN");
  linkEN.setAttribute("class", "navigation-item");
  linkEN.innerHTML = "EN";
  linkEN.style.paddingRight = "0px";
  navLinkEN.append(linkEN);
  links.append(navLinkEN);
  navBar.append(links);
  // Get language
  let href = window.location.href;
  let url = new URL(href);
  let lang = url.searchParams.get('lang');
  if (lang == 'EN' ) {
    document.getElementById('hero-title').innerHTML = 'I’m 3D augmented reality buildings in Liepaja';
    document.getElementById('share').innerHTML = 'Share:';
    document.getElementById('subheading').innerHTML = `Get to know the history of Liepaja with "3D ēkas Liepājā"`;
    let about = document.getElementById('about-project');
    about.firstElementChild.remove();
    about.insertAdjacentHTML("afterbegin",`<div class="rich-txt-blog w-richtext"><p>We have created an application "3D ēkas Liepājā", with the help of which Liepaja residents and city guests will have the opportunity to view 3 historic Liepaja buildings on their smartphone, using augmented reality technology:</p><ul role="list"><li>Society house;</li><li>Provisional Government House;</li><li>Town hall.</li></ul><p>The project "Liepaja historic architectural reconstruction augmentētajā reality" has been created with Liepaja Culture Department support.</p><p>Project goals:</p><ul role="list"><li>To promote the development of a creative, intellectual and innovative environment in Liepāja municipality for the professional growth of representatives of creative industries.</li><li>To promote local patriotism of Liepaja residents.</li><li>Develop a body of knowledge that promotes digital literacy, enabling technology to be used as an effective tool for professional activities and content consumption.</li><li>To promote the professional development of the representatives of the architecture industry and the possibilities of using augmented reality in professional activities.</li></ul></div>`);
    document.getElementById('webinar-heading').innerHTML = 'Apply for the webinar';
    document.getElementById('paragraph-webinar').firstElementChild.innerHTML = '29.04. at 18:00 webinar will take place on the augmented reality capabilities and project development progress. Apply for the webinar and receive a reminder email with a link to connect.';
    document.getElementById('btn-txt-webinar').innerHTML = 'Apply for the webinar';
    document.getElementById('app-heading').innerHTML = 'The app is available here:';
    document.getElementById('btn-ios').innerHTML = 'Download iOS app';
    document.getElementById('btn-android').innerHTML = 'Download Android app';
    document.getElementById('building-heading').innerHTML = 'About buildings';
    let firstBuilding = document.getElementById('building-first');
    firstBuilding.firstElementChild.remove();
    firstBuilding.insertAdjacentHTML("afterbegin",`<div class="rich-txt-blog w-richtext"><p><strong>Provisional Government House</strong></p><p>This building, which has been restored to augmented reality, is a building at Lielā Street 6. At the beginning of 1919, the Provisional Government of Latvia and its Prime Minister Kārlis Ulmanis stayed there. The house was built in 1912 and was one of the properties of a wealthy merchant. The house had shops, offices and apartments. When the merchant went bankrupt, he sold the house at Lielās Street 6 to J.Rusinieks, and the building became a watch wholesaler with a factory building in the yard. When Liepaja became the capital of Latvia and the government came here, this house became Kārlis Ulmanis study and meeting room. As a result of the April 16 coup, after which the government of A. Niedra was founded, all institutions of the Latvian government were destroyed. In order to survive, the government was forced to hide on ship "Saratov". In 1934, a memorial plaque was erected near the building on Lielās Street, commemorating the events of the 1919 coup and overcoming them, but the house was destroyed during World War II.<br></p></div>`);
    let secondBuilding = document.getElementById('building-second');
    secondBuilding.firstElementChild.remove();
    secondBuilding.insertAdjacentHTML("afterbegin",`<div class="rich-txt-blog w-richtext"><p><strong>Liepaja City Hall</strong></p><p>It was built in 1750 and its history is quite colorful. The house was built by a rich Liepaja resident - Meier and it had only one floor. Later, the Duke of Courland, wholesaler Stenders, stayed there, but in 1800 the house was used for the needs of the town hall. The house kept the city's archives, historical artifacts, as well as regular exhibitions, celebrations, and a pub and a city savings bank. During various city festivals and events, the house was beautifully decorated. Unfortunately, it ended when it was bombed - in 1941.<br></p></div>`);
    let thirdBuilding = document.getElementById('building-third');
    thirdBuilding.firstElementChild.remove();
    thirdBuilding.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p><strong>Liepaja Latvian Society House</strong></p><p>The former building of the Liepāja Latvian Society will also be viewed in augmented reality. In 1860, a rental house was built, which was later rented out to the Liepaja Latvian Society House. The society house was responsible for all the city's public events. When the Society House moved to the current building in Rožu Square, the tenement house became a cultural center with hobby groups, choir rehearsals, and a stage orchestra office. The building was no longer in good technical condition, so it was demolished around 1980.</p></div>`);
    document.getElementById('instruction-heading').innerHTML =  'Instructions for use';
    let instructionMain = document.getElementById('instruction-main');
    instructionMain.firstElementChild.remove();
    instructionMain.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p>To view 3D buildings, you must allow app to access location and camera. When you are close enough, you will be able to place the buildings in augmented reality. On different devices, buildings can be located in different places, depending on the performance of the smartphone, weather, environment, GPS signal. During the dark hours of the day or near buildings that obscure the signal, the app may malfunction.</p><p>The buildings can be viewed in 2 ways - by placing small building models on any plane or in 3 locations Liepaja (historical locations of buildings).</p><ul role="list"><li>Approaching their location in the city.</li><li>In any indoor. Open the app, select that you want to see 3D buildings premises. You will be able to place the buildings in the place you want and see them.</li></ul></div>`);
    document.getElementById('developers-heading').innerHTML = 'Project developed by';
    let developerJanis = document.getElementById('info-janis');
    developerJanis.firstElementChild.remove();
    developerJanis.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p><strong>Jānis Jaunsleinis</strong> – 3D architecture developer:</p><ul role="list"><li>Participated in the creation of a 3D model for the construction section for the reconstruction of Riga Technical University;&nbsp;</li><li>Created visualizations of buildings energy efficiency improvement projects;</li><li>He has researched many sources of pre-war photography and history of the city of Liepaja, therefore with the help of augmented reality and 3D modelling he can revive the lost architecture give people the opportunity to see the features of historical buildings.&nbsp;&nbsp;</li></ul></div>`);
    document.getElementById('how-city-heading').innerHTML = 'How to see buildings in an urban environment?';
    let howCity = document.getElementById('how-city-paragraph');
    howCity.firstElementChild.remove();
    howCity.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p>To view any building in the urban environment, it is necessary to be located at the historical location of the building, closer than 50m. Once you closer than 50m to the available building button will display the message "Insert buildings" or when marker is used "View of buildings."</p><p>Two of the three objects use red guides that must be used to place buildings in their old location, while the third building uses marker technology that inserts the building when the marker is recognized.</p></div>`);
    document.getElementById('how-building-1-heading').innerHTML = 'How to view Provisional Government House?';
    document.getElementById('step-1-1').innerHTML = 'Step 1';
    document.getElementById('step-1-2').innerHTML = 'Step 2';
    document.getElementById('step-1-3').innerHTML = 'Step 3';
    document.getElementById('txt-1-1').innerHTML = 'Go to the address Lielā Street 3, Liepāja';
    document.getElementById('txt-1-2').innerHTML = 'Stand here with a view across the street';
    document.getElementById('txt-1-3').innerHTML = 'Position the phone so that the red guides correspond to the corner of Lielās Street 4 building and press the "Insert" button';
    document.getElementById('how-building-2-heading').innerHTML = 'How to view Town hall?';
    document.getElementById('step-2-1').innerHTML = 'Step 1';
    document.getElementById('step-2-2').innerHTML = 'Step 2';
    document.getElementById('step-2-3').innerHTML = 'Step 3';
    document.getElementById('txt-2-1').innerHTML = 'Go to the address Lielā iela 12, Liepāja (at the store "Drogas", right at the bakery)';
    document.getElementById('txt-2-2').innerHTML = 'Stand here with a view across the street to the hotel "Līva"';
    document.getElementById('txt-2-3').innerHTML = 'Position the phone so that the red guides correspond to the corner of the hotel "Līva" and press the "Insert" button';
    document.getElementById('how-building-3-heading').innerHTML = 'How to view Society house?';
    document.getElementById('step-3-1').innerHTML = 'Step 1';
    document.getElementById('step-3-2').innerHTML = 'Step 2';
    document.getElementById('txt-3-1').innerHTML = 'Head to the intersection of Ludviķa and Avotu streets, Liepāja';
    document.getElementById('txt-3-2').innerHTML = 'Stand in position 1 with a view of the "Benu aptieka" advertisement (2) - the advertisement is a marker';
    document.getElementById('how-plane-heading').innerHTML = 'How to view buildings on a plane?'
    let howPlane = document.getElementById('how-plane-paragraph');
    howPlane.firstElementChild.remove();
    howPlane.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p>You can also view all buildings in a small size by placing them on a plane/floor/ground. It is best to place the buildings in spacious rooms or outdoors.</p><ol start="" role="list"><li>Open the app "3D ēkas Liepājā";</li><li>Find a free plane;</li><li>Wait at least 6 seconds for the phone to detect the plane. When the phone recognizes the plane, place the buildings on it (the larger the blue circle of the indicator, the larger the building will be on the plane). It is possible to get around the building and view it from all sides.</li></ol></div>`);
    let developerKaspars = document.getElementById('info-kaspars');
    developerKaspars.firstElementChild.remove();
    developerKaspars.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p><strong>Kaspars Lēvalds</strong> – multimedia artist.</p><p>Kaspars:</p><ul role="list"><li>Graduate of the University of Liepaja, in the program New Media Art;</li><li>Within and outside the studies, he has created and participated in the creation of various augmented reality (VR, AR) works;</li><li>Participated in Augmented and Virtual Reality Hackathon 2018 and RIGA IFF GOES VR (2019), where together with the teams they gained the first and second place in creating virtual reality experiences;</li><li>Creates a variety of digital visual works – design and architecture and other types, using Unity and Unreal Engine game drivers.</li></ul></div>`);
    let developerArturs = document.getElementById('info-arturs');
    developerArturs.firstElementChild.remove();
    developerArturs.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog w-richtext"><p><strong>Arturs Vītiņš</strong> – programmer, augmented reality developer.</p><p>Arturs ir:</p><ul role="list"><li>For several years working as a civil engineer building design Ltd. AILE group;</li><li>Know several programming languages;</li><li>The project developed an application in the Unity environment for iOS and Android devices, as well as created augmented reality solutions.</li></ul></div>`);
    let eula = document.getElementById('eula');
    eula.firstElementChild.remove();
    eula.insertAdjacentHTML("afterbegin", `<div class="rich-txt-blog txt_align_centred mt_80 w-richtext"><p><a href="/projekti/3d-ekas-liepaja-gala-lietotaja-licences-ligums">EULA</a></p><p><a href="/projekti/liepaja-ar-gala-lietotaja-licences-ligums">&zwj;</a><a href="https://www.digip.lv/projekti/liepaja-ar-gala-lietotaja-licences-ligums"><strong>&zwj;</strong></a>Use email address <a href="mailto:team@digip.lv">team@digip.lv</a>, to contact us in case of uncertainty, in matters related to marketing and when you need support.</p><p>&zwj;</p></div>`);
    document.getElementById('txt-liepaja').innerHTML = 'The app is supported by the Liepaja Culture Department';
    document.getElementById('txt-museum').innerHTML = 'The application was created in cooperation with the Liepaja Museum';
  }
}
